apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-pr-minting
  namespace: default
spec:
  # 1. Schedule: Runs every five minutes (e.g., at 0, 5, 10, 15... minutes past the hour)
  schedule: "0 */8 * * *"
  # schedule: "*/5 * * * *"

  # 2. Job Template: Defines the Job that will be run on schedule
  jobTemplate:
    spec:
      # Pod Template: Defines the Pod that runs the container
      template:
        spec:
          # Restart policy for the Pod in the Job
          restartPolicy: Never
          tolerations:
          - key: "node-role.kubernetes.io/control-plane"
            operator: "Exists"
            effect: "NoSchedule"
          containers:
          - name: cron-container
            # Use a lightweight image like busybox for simple scripts
            image: quay.io/jchaloup/prlabeler:0.7
            # The command to execute on the schedule
            command:
            - /bin/prlabeler
            args:
            - "--repository=openshift/cluster-kube-descheduler-operator"
            - "--repository=openshift/descheduler"
            - "--repository=openshift/secondary-scheduler-operator"
            - "--repository=openshift/run-once-duration-override-operator"
            - "--repository=openshift/run-once-duration-override"
            - "--repository=openshift/cli-manager-operator"
            - "--repository=openshift/cli-manager"
            env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secret
                  key: api_token

  # ConcurrencyPolicy: Defines how to handle concurrent job executions.
  # Options: Allow (default), Forbid, Replace
  concurrencyPolicy: Forbid

  # SuccessfulJobsHistoryLimit: Number of successful finished jobs to keep.
  successfulJobsHistoryLimit: 3

  # FailedJobsHistoryLimit: Number of failed finished jobs to keep.
  failedJobsHistoryLimit: 3
